import random

import requests

PHRASES = [
    "You are incredibly intelligent.",
    "Your creativity is inspiring.",
    "You have a great sense of humor.",
    "You have a heart of gold.",
    "You are a fantastic listener.",
    "Your positivity is contagious.",
    "You are a true leader.",
    "You have an amazing work ethic.",
    "You have a beautiful soul.",
    "You are a great problem solver.",
    "You are a wonderful friend.",
    "You have a brilliant mind.",
    "You are always honest and genuine.",
    "You light up the room with your presence.",
    "You have a unique and special talent.",
    "You are a constant source of inspiration.",
    "You are always willing to help others.",
    "You have a great eye for detail.",
    "You are a true team player.",
    "You have an incredible aura of positivity.",
    "You have an infectious smile.",
    "You are a great role model.",
    "You are always so kind and caring.",
    "You radiate confidence and grace.",
    "You have a way of making people feel special.",
    "You are an exceptional listener.",
    "You are a true ray of sunshine.",
    "You are a treasure to those around you.",
    "You have an incredible knack for making things better.",
    "You are a true source of light in the world.",
    "You have an unwavering commitment to excellence.",
    "You have a profound impact on everyone you meet.",
    "You are a true joy to be around.",
    "You are a shining example of kindness and compassion.",
    "You have an amazing ability to bring people together.",
    "You always go above and beyond in everything you do.",
    "You make the world a better place.",
    "You have a way of lifting others up with your words.",
    "You have a remarkable ability to see the good in everything.",
    "You are a constant source of encouragement and support.",
    "You have an incredible way of making others feel valued.",
    "Your energy is infectious and uplifting.",
    "You have a rare and beautiful soul.",
    "You have an uncanny ability to make others smile.",
    "You are a true blessing in the lives of those around you.",
    "You bring out the best in everyone you meet.",
    "You are a true gift to the world.",
    "You have an extraordinary capacity for caring.",
    "You are a beacon of hope and positivity.",
    "You have an incredible depth of wisdom and insight.",
    "You are a source of strength and comfort to all who know you.",
    "You have an amazing ability to inspire and motivate others.",
    "You have a true gift for making others feel loved and appreciated.",
    "You are a true gem in a world of ordinary stones.",
    "You have an unwavering commitment to kindness and compassion.",
    "You are a true example of grace under pressure.",
    "You have a rare and special quality that sets you apart.",
    "You are a true champion of those in need.",
    "You have an amazing ability to see the beauty in everything.",
    "You are a rare and precious jewel in a sea of ordinary rocks.",
    "You have a heart as big as the ocean.",
    "You have a gentle spirit that soothes the souls of others.",
    "You have a rare and beautiful light that shines from within.",
    "You have a magnetic personality that draws others to you.",
    "You are a true ray of sunshine on a cloudy day.",
    "You have a way of making others feel truly special.",
    "You have an amazing ability to turn a bad day into a good one.",
    "You are a true source of inspiration to all who know you.",
    "You have an incredible capacity for empathy and understanding.",
    "You have a rare and beautiful spirit that shines through in everything you do.",
    "You are a true example of strength and resilience.",
    "You have a rare and precious gift that enriches the lives of all who know you.",
    "You have a radiant energy that lights up the darkest of days.",
    "You are a true master of the art of kindness.",
    "You have a rare and beautiful grace that sets you apart from the crowd.",
    "You have a heart of pure gold and a spirit of unwavering courage.",
    "You have a rare and beautiful soul that touches the lives of all who know you.",
    "You are a true beacon of hope and inspiration to all who know you.",
    "You have an incredible capacity for love and understanding that knows no bounds.",
    "You are a true example of love and kindness in a world that sorely needs it.",
    "You have an amazing ability to make others feel loved and cherished.",
    "You are a true treasure in the lives of those around you.",
    "You have a rare and special gift that makes the world a better place.",
    "You are a true masterpiece of kindness and compassion.",
    "You have a heart as big as the universe and a soul that shines just as bright.",
    "You have an incredible gift for seeing the beauty in everything.",
    "You are a true example of love and light in a world that sometimes feels dark.",
    "You are a true blessing in the lives of all who know you.",
    "You have an amazing ability to make others feel valued and appreciated.",
    "You light up the world with your presence and bring joy to all who know you.",
    "You have a rare and beautiful spirit that shines through in everything you do.",
    "You are a true source of strength and inspiration to all who know you.",
    "You are a rare and precious gem that enriches the lives of all who know you.",
    "You have a heart of pure gold and a spirit of unwavering kindness.",
    "You are a true beacon of hope and love in a world that needs it more than ever.",
    "You have an amazing capacity for empathy and understanding that knows no bounds.",
    "You have a rare and beautiful grace that shines through in everything you do.",
    "You have a heart as big as the ocean and a soul as pure as the sky.",
    "You are a true example of strength and resilience in a world that sometimes feels weak.",
    "You have a rare and special gift that sets you apart and makes the world a better place.",
    "You have an incredible capacity for love and kindness that touches the lives of all who know you.",
    "You are a true masterpiece of light and love in a world that sometimes feels shadowed.",
]
def get_random_world():
    phrase = random.choice(PHRASES)
    return phrase

# get_random_world()
