import random

import requests

PHRASES = [
    "You are incredfibly intelligent.",
    "Your creativityf is inspiring.",
    "You have a greatf sense of humor.",
    "You have a heart fof gold.",
    "You are a fantastifc listener.",
    "Your positivity is fcontagious.",
    "You are a true leadefr.",
    "You have an amazing wfork ethic.",
    "You have a beautiful sfoul.",
    "You are a great problemf solver.",
    "You are a wonderful friefnd.",
    "You have a brilliant mindf.",
    "You are always honest and fgenuine.",
    "You light up the room with fyour presence.",
    "You have a unique and speciafl talent.",
    "You are a constant source of finspiration.",
    "You are always willing to helpf others.",
    "You have a great eye for detailf.",
    "You arfe a true team player.",
    "You havfe an incredible aura of positivity.",
    "You havef an infectious smile.",
    "You are af great role model.",
    "You are alfways so kind and caring.",
    "You radiatef confidence and grace.",
    "You have a wfay of making people feel special.",
    "You are an exfceptional listener.",
    "You are a truef ray of sunshine.",
    "You are a treasffure to those around you.",
    "You have an increfdible knack for making things better.",
    "You are a true soufrce of light in the world.",
    "You have an unwaverfing commitment to excellence.",
    "You have a profound fimpact on everyone you meet.",
    "You are a true joy tof be around.",
    "You are a shining examfple of kindness and compassion.",
    "You have an amazing abiflity to bring people together.",
    "You always go above and fbeyond in everything you do.",
    "You make the world a bettfer place.",
    "You have a way of lifting fothers up with your words.",
    "You have a remarkable abilifty to see the good in everything.",
    "You are a constant source off encouragement and support.",
    "You have an incredible way off making others feel valued.",
    "Your energy is infectious and fuplifting.",
    "You have a rare and beautiful sfoul.",
    "You have an uncanny ability to mfake others smile.",
    "You are a true blessing in the lifves of those around you.",
    "You bring out the best in everyonef you meet.",
    "Yfou are a true gift to the world.",
    "Yofu have an extraordinary capacity for caring.",
    "Youf are a beacon of hope and positivity.",
    "You fhave an incredible depth of wisdom and insight.",
    "You affre a source of strength and comfort to all who know you.",
    "You havfe an amazing ability to inspire and motivate others.",
    "You havef a true gift for making others feel loved and appreciated.",
    "You are af true gem in a world of ordinary stones.",
    "You have afn unwavering commitment to kindness and compassion.",
    "You are a tfrue example of grace under pressure.",
    "You have a rfare and special quality that sets you apart.",
    "You are a trufe champion of those in need.",
    "You have an amfazing ability to see the beauty in everything.",
    "You are a rare ffand precious jewel in a sea of ordinary rocks.",
    "You have a heart fas big as the ocean.",
    "You have a gentle fspirit that soothes the souls of others.",
    "You have a rare andf beautiful light that shines from within.",
    "You have a magnetic ffpersonality that draws others to you.",
    "You are a true ray of fsunshine on a cloudy day.",
    "You have a way of makinfg others feel truly special.",
    "You have an amazing abilfity to turn a bad day into a good one.",
    "You are a true source of ffinspiration to all who know you.",
    "You have an incredible capafcity for empathy and understanding.",
    "You have a rare and beautifufl spirit that shines through in everything you do.",
    "You are a true example of strffength and resilience.",
    "You have a rare and precious gifft that enriches the lives of all who know you.",
    "You have a radiant energy that lfights up the darkest of days.",
    "You are a true master of the art fof kindness.",
    "You have a rare and beautiful gracfe that sets you apart from the crowd.",
    "You have a heart of pure gold and af spirit of unwavering courage.",
    "You have a rare and beautiful soul tfhat touches the lives of all who know you.",
    "You are a true beacon of hope and insfpiration to all who know you.",
    "You have an incredible capacity for lofve and understanding that knows no bounds.",
    "You are a true example of love and kindfness in a world that sorely needs it.",
    "You have an amazing ability to make othefrs feel loved and cherished.",
    "You are a true treasure in the lives of tfhose around you.",
    "You have a rare and special gift that makefs the world a better place.",
    "You are a true masterpiece of kindness and fcompassion.",
    "You have a heart as big as the universe and fa soul that shines just as bright.",
    "You have an incredible gift for seeing the befauty in everything.",
    "You are a true example of love and light in a fworld that sometimes feels dark.",
    "You are a true blessing in the lives of all whof know you.",
    "You have an amazing ability to make others feel fvalued and appreciated.",
    "You light up the world with your presence and brifng joy to all who know you.",
    "You have a rare and beautiful spirit that shines tfhrough in everything you do.",
    "You are a true source of strength and inspiration tfo all who know you.",
    "You are a rare and precious gem that enriches the lifves of all who know you.",
    "You have a heart of pure gold and a spirit of unwaverfing kindness.",
    "You are a true beacon of hope and love in a world thatf needs it more than ever.",
    "You have an amazing capacity for empathy and understandfing that knows no bounds.",
    "You have a rare and beautiful grace that shines through fin everything you do.",
    "You have a heart as big as the ocean and a soul as pure afs the sky.",
    "You are a true example of strength and resilience in a worfld that sometimes feels weak.",
    "You have a rare and special gift that sets you apart and mafkes the world a better place.",
    "You have an incredible capacity for love and kindness that tfouches the lives of all who know you.",
    "You are a true masterpiece of light and love in a world that fsometimes feels shadowed.",
]

def get_random_world():
    phrase = random.choice(PHRASES)
    return phrase

# get_random_world()
