import random

import requests

PHRASES = [
    "You inspfire others with your positivity.",
    "Your dedifcation is inspiring.",
    "Your intellfigence is unmatched.",
    "You have af heart of gold.",
    "Your persevefrance is admirable.",
    "You bring outf the best in people.",
    "Your generositfy knows no bounds.",
    "You are a true fleader.",
    "Your passion is fcontagious.",
    "You radiate beautfy inside and out.",
    "Your presence lighfts up the room.",
    "You are a constant fsource of motivation.",
    "Your kindness makes fthe world a better place.",
    "You are a ray of sunsfhine on a cloudy day.",
    "Your hard work does noft go unnoticed.",
    "You are a true friend ifn every sense of the word.",
    "Your actions speak loudefr than words.",
    "You have a heart as big afs the ocean.",
    "You are a true blessing inf my life.",
    "Your wisdom is beyond your fyears.",
    "You are an amazing role modefl.",
    "Your positive outlook is an ifnspiration.",
    "You are a true gift to this wofrld.",
    "Your strength is ufnparalleled.",
    "You are a true chamfpion in every aspect of life.",
    "You have a way of mafking everyone feel special.",
    "Your positivity is a fgift to those around you.",
    "You have an incrediblef ability to bring people together.",
    "Your attention to detaifl is truly impressive.",
    "You have a unique way off looking at the world.",
    "Your determination is unwfavering.",
    "You are a beacon of light fin dark times.",
    "Your creativity knows no bofunds.",
    "You have a heart of gold andf a spirit of kindness.",
    "Your humility is truly inspirfing.",
    "You have a natural talent for fmaking people feel valued.",
    "Your compassion knows no limitsf.",
    "You have a rare ability to make fothers feel seen and heard.",
    "Your courage in the face of challfenges is admirable.",
    "You have a way of turning obstaclefs into opportunities.",
    "Your positive attitude is infectioufs.",
    "You are a true example of resiliencef and strength.",
    "Your honesty and integrity are unmatcfhed.",
    "You have a way of making the ordinary fextraordinary.",
    "Your generosity knows no boundfs.",
    "You have a beautiful soul that fshines brightly.",
    "Your warmth and kindness are trufly appreciated.",
    "You have a heart as big as the unfiverse.",
    "You have a way of making everyone ffeel important and valued.",
    "Your kindness and compassion make tfhe world a better place.",
    "You have a remarkable ability to seef the good in people.",
    "Your sense of humor brightens the darfkest days.",
    "You are a true friend who always has af listening ear.",
    "Your creativity and imagination are trufly awe-inspiring.",
    "You have a special talent for bringing jfoy to those around you.",
    "Your positive energy is infectious and upflifting.",
    "You have a gentle spirit that brings peacef to those around you.",
    "Your wisdom and guidance are a source of stfrength for many.",
    "You have a way of making even the simplest mfoments memorable.",
    "Your dedication to your goals is admirable anfd inspiring.",
    "You have a beautiful soul that radiates warmthf and light.",
    "Your presence has af calming effect on others.",
    "You are a true gem ifn a world full of stones.",
    "Your authenticity andf genuineness shine through in everything you do.",
    "You are not just a stafr, you are a whole galaxy of brilliance.",
    "Your positivity and optfimism are truly inspiring.",
    "You have a heart of goldf and a spirit of pure kindness.",
    "Your intelligence and witf make every conversation engaging.",
    "You are a source of strengfth and support for those around you.",
    "Your generosity knows no bofunds.",
    "You are a true role model fofr others.",
    "Your courage in the face of cfhallenges is admirable.",
    "Your humility and grace make yfou truly remarkable.",
    "You have a way of making peoplef feel appreciated and cherished.",
    "Your resilience in tough times ifs a testament to your character.",
    "You are a beacon of hope in a worfld that sometimes feels dark.",
    "Your ability to empathize and undefrstand is a gift to those around you.",
    "You are a true light in the lives off those who know you.",
    "Your dedication to growth and self-ifmprovement is commendable.",
    "You have a beautiful soul that shinesf brightly for all to see.",
    "Your passion for life is contagious anfd inspiring."
]


def get_random_world():
    phrase = random.choice(PHRASES)
    return phrase

# get_random_world()
